### ISSUE TITLE
Integration with Airtable and Hubspot

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/customer-success#116]
## To-Do
- [x] Get Evan's sign-off to integrate with the [California Transit Organization table](https://airtable.com/appPnJWrQ7ui4UmIl/tblFsd8D5oFRqep8Z/viw5xgjoVdHE5o8ZP?blocks=hide)
- [x] Review and discuss [Airtable / Hubspot integration](https://app.hubspot.com/ecosystem/5519226/marketplace/apps/productivity/project-management/airtable-data-sync4)
- [x] Setup a meeting with the permissions group (Evan, Anthony, Kegan, E, Laurie, Scott F., Scott O., Alyssa) for the week of 9/5
- [ ] Setup and test integration. `Airtable Name Field` > `Hubspot Company Name` `Airtable website domain` > `Hubspot Company domain name`

**Comment by AnthonyRollins** [comment]
@evansiroky @e-lo We are looking to use [Hubspot's integration with Airtable](https://app.hubspot.com/ecosystem/5519226/marketplace/apps/productivity/project-management/airtable-data-sync4) to sync data one-way with the [California Transit Organizations](https://airtable.com/appPnJWrQ7ui4UmIl/tblFsd8D5oFRqep8Z/viwhhibWpFXRJ7nYc?blocks=hide) table, mainly linking the "Name" field and "website domain name." 

Any issue with us creating this integration and using a one-way sync with Hubspot as the primary data input? I want to ensure the CRM is where information about companies is updated and passed on to Airtable. 

Let me know if there is anything else you need from me or if I should include anyone else.

**Comment by safrazier17** [comment]
I think I'm confused about what you said about having the CRM be the Source of Truth for some but not all data @AnthonyRollins. Isn't airtable what is feeding most of our reports and interfaces? I would think that we would want to have airtable be the source of truth and have the ability to overwrite data in there via CRM.

Can you help me understand what I'm missing? Or we can set up a call

**Comment by AnthonyRollins** [comment]
That works for me to overwrite (contact info) data in Airtable via the CRM, as long as it doesn't mess up anything with Metabase / Data warehouse. I think people using the CRM for outreach will want to update transit agencies and transit agencies' staff in Hubspot. I created this [spreadsheet](https://docs.google.com/spreadsheets/d/1ZvU4WWS2K1QEtRIk16M83Xnv8X3-wPTB9Mkci_ZLyBE/edit#gid=0) for all the properties I think should be updated and managed within the CRM, not sure if you saw this. I see you put some time for all of us to chat, @safrazier17 more and more questions come up about this, and it would be great to talk with everyone. Thanks for making that happen!

**Comment by AnthonyRollins** [comment]
Kegan and I are meeting on August 31st to talk through integration.

**Comment by thekaveman** [comment]
@evansiroky @e-lo -- @AnthonyRollins and I are meeting on the Airtable <> Hubspot integration for the _Organizations contact info_ and have a question/request for you:

The integration requires a `Last modified time` type column on both sides; we have this in Hubspot but not in Airtable:

![image](https://user-images.githubusercontent.com/1783439/187752802-19b53d14-ecbf-473a-b45b-82f0036f0110.png)

Is it possible to add a column like that to the `organizations` table in Airtable? E.g. something that auto-updates each time a field in a particular column is edited?

**Comment by e-lo** [comment]
❓ The Airtable [last modified field calculation ](https://support.airtable.com/docs/last-modified-time-field)allows for you to specify which fields you "care about" being modified.  Should we select "all"?

❓ Should we as a practice just add a field named `last modified` to all tables?

**Comment by evansiroky** [comment]
Pending feedback to @e-lo's questions, I'm happy to add the field. I'm also curious what things would happen if anything given the last update field being used. I would assume that we'd only want to add this field to the organizations table.

**Comment by thekaveman** [comment]
> ❓ The Airtable [last modified field calculation ](https://support.airtable.com/docs/last-modified-time-field)allows for you to specify which fields you "care about" being modified. Should we select "all" or should we be pickier?

That looks promising! I think our initial goal was to sync FROM Hubspot TO Airtable, for the couple of fields that should be maintained in Hubspot. To that end, I can see an argument for making the `last modified` only "watch" those couple of fields...

I assume we can edit that "watch" definition later? I have some follow-up thoughts/questions but I think if we can get that field added so we can see what the integration looks like past that screenshot, it would be a good start. 

> ❓ Should we as a practice just add a field named `last modified` to all tables?

That _seems_ like a good idea to me... but I'm certainly no Airtable expert (or really even a user!)

**Comment by lauriemerrell** [comment]
Hopping in here because @thekaveman flagged this discussion on https://github.com/cal-itp/data-infra/issues/1731#issuecomment-1233472496. 

* Re: all fields or subset of fields -- I mostly think we would just want to have very clear documentation/labeling for this (especially if we brought this field into the warehouse). If it's only watching synced fields, maybe we could name it something different (like `sync_last_modified` or `crm_last_modified` or something like that), just because I do think people would usually assume that something called `last_modified` without any scope label would apply to any time anything on the record was modified. That's definitely just my opinion, though.
* I will be curious to see how "noisy" this is (like, does it register things as "updates" that human users might not expect re: data linking or syncing).... I think somewhere we had a version of this conversation about how the warehouse can do snapshot-based versioning right now, I wonder if we can possibly use that to compare with this field after it's been live for a bit and just see how interpretable it is.

I don't think there's a warehouse concern with creating such a field, as long as we are very clear about documentation as described in first bullet.

**Comment by thekaveman** [comment]
@e-lo @evansiroky @lauriemerrell To get us started with the Hubspot --> Airtable sync (really just to see how it works), we're totally fine with a `crm_last_updated` or similar column that only watches the few columns that we will push over (really just name and URL to start).

----

The other question I had maybe more for @evansiroky and @e-lo -- is it possible to make certain fields in Airtable read-only, or maybe read-only for a specific role/group of users? Our thought was to mark these Hubspot-originated fields as read-only if possible, to reduce the chance of getting out of date and to reinforce Hubspot as the place to maintain that info.

**Comment by AnthonyRollins** [comment]
@thekaveman Got the test integration working on [Hubspot](https://app.hubspot.com/data-sync/5519226/app/236654/account/435547/settings). Let me know if there is anything else we should look into on this. 

Thanks, @evansiroky, for adding the `bot@calitp.org` account as an owner. This integration found a lot of duplicates in Hubspot that we can use to figure out how we will merge them.

**Comment by AnthonyRollins** [comment]
@thekaveman Not sure if you have heard anything about this, but we wanted to bring this conversation back to see if there are any next steps with integration with the warehouse. It might be something we shoot a message over to Laurie, Evan and Scott F, but we wanted to start here first.

cc: @o-ram

**Comment by AnthonyRollins** [comment]
Replaced with #445
