### ISSUE TITLE
Prepare Hubspot for Cal-ITP Newsletters

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/customer-success#152]
## To-Do
- [ ] Export data from Constant Contact
- [ ] Import data into Hubspot
- [ ] Create a new subscriber list in Hubspot
- [ ] Add import to the new subscriber list
- [ ] Prepare first monthly email

**Comment by o-ram** [comment]
@AnthonyRollins let's think about reworking this ticket. I dropped the idea of moving the newsletter into Hubspot in a weekly call with Gillian and got a pretty good reaction, especially from her. In which case, I imagine we would want to move the subscriber list into Hubspot and redo the sign-up form. So instead of talking integration, we're moving things over and can create tickets for that instead and either repurpose or close this one.

**Comment by AnthonyRollins** [comment]
@o-ram If there is a strong interest in bringing this to Hubspot, let's figure this out during our call on Monday and update this issue and potentially create more. We already have a lot of Constant Contact data on Hubspot, but it might be worth a refresher.

**Comment by AnthonyRollins** [comment]
@o-ram I updated this ticket to prepare to handle the newsletter in Hubspot.
