### ISSUE TITLE
Create system for tracking and creating outstanding training guides

### ISSUE THREAD

**Issue by laneymangan** [cal-itp/customer-success#264]
- [x] organize training guide tracker
- [ ] create outstanding training guides in scribe
- [ ] convert guides to doc
- [ ] convert guides to web version
- [ ] ensure all guides are linked in [CRM Guide](https://docs.google.com/document/d/11SIWzGqDDJN4OADASiXywvcu9C8deXZRvTE-cdn-Lh4/edit#heading=h.sj009bso7kf7)

**Comment by o-ram** [comment]
linking the [github issue template training guide](https://docs.google.com/document/d/1TxpzTHkLkZZFIprZta2aELpNAwKfvRrc7yVICpjaELw/edit) here as well, in case it's relevant for training guide organization/inventory.

**Comment by AnthonyRollins** [comment]
@laneymangan, should we plan to work on this again in 2024? These appears to be an issue for a larger CRM Guide maintenance.

**Comment by laneymangan** [comment]
Priority Training Guides: 
- [ ] reports subscription training guide

**Comment by AnthonyRollins** [comment]
Future direction for the CRM is needed before pursuing changes.
