### ISSUE TITLE
Onboarding for Account Manager: weeks 1-2 checklist

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/customer-success#279]
July 11th our new Account manager for Customer Success will start, and this ticket plans out the first week-2 weeks of onboarding materials specific to Cal-ITP Account Manager work.

**General Cal-ITP information:**
- [x] [Cal-ITP “Start Here” guide](https://docs.google.com/document/d/1dpjjNSdmnAejpsw4RAdbNzFBOdxlNO_-1KWxwb96cVI/edit)
- [x] [Caltrans Strategic Plan](https://dot.ca.gov/-/media/dot-media/programs/risk-strategic-management/documents/sp-2020-16p-web-a11y.pdf) (**Optional**, For high-level understanding of what’s happening at Caltrans)
- [ ] [PMP Strategic Plan](https://dot.ca.gov/-/media/dot-media/programs/planning-modal/documents/pandmp-sp-2020-24-a11y.pdf) (**Optional**, For high-level understanding of what’s happening at Caltrans)
- [ ] [Interview with Gillian](https://www.intelligenttransport.com/transport-articles/131081/california-taps-into-the-future-of-fare-collection/ ) (Cal-ITP Program Manager/Chief of Caltrans Division of Data and Digital Services)
- [x] [About Cal-ITP standard deck](https://docs.google.com/presentation/d/1Yi0zdZ3uiQ9XyiPfePRW4Dtu-ALiP12YFqXD5Xv_LoI/edit?usp=drive_link)
- [x] Roadmap _(link needed from Jess)_
- [x] #188 
- [x] [CRM Guide](https://docs.google.com/document/d/11SIWzGqDDJN4OADASiXywvcu9C8deXZRvTE-cdn-Lh4/edit#heading=h.q9i1mqgcc13q) (**Optional**, Do not need to read all of it right away, but helpful to have at hand as familiar with how we use HubSpot increases)
- [x] Obtain a HubSpot account
- [x] Make a Github account

**Customer Success team/Account Manager information:**
- [x] [Account Manager Training Guide](https://docs.google.com/document/d/18u62_Cz9DV3UqrlAreXqpbirlo0cN4KzWONfDLrTKrE/edit#heading=h.cfwavlj00dpn) in its current state
- [x] [Team OKRs](https://docs.google.com/document/d/1a5_pRT1mb_MWpgxPRiVxpMwiMQ7JAdhdAa7m9jidSms/edit)
- [x] [Customer Success philosophy](https://docs.google.com/document/d/1Pe4P6qoD8O-YLP0BJLpqSYaYxBv-9oOMucDbyqLzwMM/edit?usp=drive_link)
- [x] [Menu of Services](https://docs.google.com/document/d/118-tOm14bgIWXtiBx_rZ-Picxdv9JqpD4PS7WXjkoiM/edit)
- [x] Google Drive: [Customer Success folder](https://drive.google.com/drive/folders/17WChuEjB4_veWBlSW5uhhWpH33_N6EId) and [SOP folder](https://drive.google.com/drive/folders/150-ZfnfjdYp69eYqEoNyRBWSN2ZK2YPG)
- [x] [Cohort list](https://app.hubspot.com/contacts/5519226/objects/0-2/views/13178995/list?redirectFrom=crm-records-ui)
- [x] [Doc Catalog](https://docs.google.com/document/d/1cowfa-l3x4blDkrF8I6WmN7NHEGQHYV_8MemE0a7CUc/edit#heading=h.gtlbgaln0owh) _(this is a work in progress - specific SOPs that are important now will be conveyed)_
- [x] Agency list (introductions will come ~ week 3. For now, start with getting familiar with your assigned agencies.)
- HubSpot account needed. Once one is created, Olivia will assign Kathryn and link here to that subset of agencies.
- [ ] #290 - Joint assignment with @ProvvidenzaC  and @kathrynmsullivan 
- [ ] Time to discuss "how we communicate". 
- There is no one doc that conveys this, so this will take the place of a call where we can screenshare and provide some informal do's & don'ts as well as some helpful tips to keep in mind or have bookmarked.

**Comment by o-ram** [comment]
@AnthonyRollins I cleaned this up into a list and got rid of any links that weren't immediately relevant. Feel free to add on or we can have this issue be just intended for the first ~1-2 weeks and create new ones from there.

**Comment by AnthonyRollins** [comment]
This is great. I will add the next steps for the philosophy document to this once I create the issue today.
