### ISSUE TITLE
CALACT Pre-Conference Checklist

### ISSUE THREAD

**Issue by kathrynmsullivan** [cal-itp/customer-success#330]
This issue tracks the pre-tasks for the CALACT conference which is held November 1-3rd in Indian Wells, CA.

- [x] Confirm w/Calact about name change
- [x] What is included in the booth? 8' High Back Drape, 3' High side Rail Drape, (1) 6' Skirted Table, (2) side chairs, (1) wastebasket, 1 7' x 44' ID sign
- [x] Email orders@tricord.net to get login to order online
- [x] Order two side chairs.

**Comment by kathrynmsullivan** [comment]
The booth includes:

![Image](https://github.com/cal-itp/customer-success/assets/139281146/7cfed099-27c8-46e4-8e57-c785b130edcc)

"The ID signs do not require a logo. It is just going to be your company name centered with booth number in the bottom right hand corner. We will print the ID sign based on the list show management sends, so please be sure to let them know if anything needs to be changed."

**Comment by AnthonyRollins** [comment]
@kathrynmsullivan Should we purchase additional chairs here, so everyone has a seat?
