### ISSUE TITLE
CTA Pre-Conference Checklist 

### ISSUE THREAD

**Issue by kathrynmsullivan** [cal-itp/customer-success#331]
This issue tracks the tasks we need to complete prior to the CTA Conference

- [x] Please review, sign, and return the [Conference Conditions and Agreement by October 6.](https://caltransit.org/Portals/0/Cal%20Transit%20Conference%20Rules23.pdf?ver=uPCaKkEIFYXc2k0HekEaJw%3d%3d)
- [x] Please review [the Exhibitor Kit] to purchase a package (https://www.tricord.net/wp-content/uploads/2023/08/CTA-2023-Exhibitor-Kit.pdf) see email for password.
- [x] Complete Survey for [App](https://www.surveymonkey.com/r/G7SDBNZ) by October 13th
- [x] Please provide a high-resolution logo for your branded counter to [Tricord Graphic Upload](https://tricords.filecamp.com/s/2IYz5fhqBMEaKzuY/u) by October 6.

**Comment by AnthonyRollins** [comment]
@kathrynmsullivan, The Dropbox link for submitting a hi-res logo doesn't appear to work. Let me know if there is a better link.

**Comment by kathrynmsullivan** [comment]
@AnthonyRollins - correct, just emailed our contact at CTA for a updated link

**Comment by AnthonyRollins** [comment]
@kathrynmsullivan I checked off the agreement and hi-res logo. I believe we are still waiting on some questions from Tricord about the exhibitor kit we want to purchase.

**Comment by AnthonyRollins** [comment]
Furniture order
