### ISSUE TITLE
Conference meeting scheduler

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/customer-success#350]
## To-Dos
- [x] Add Olivia's calendar to Hubspot
- [x] Update calendar events on GCal to `Free` instead of `Busy`
- [x] Update Hubspot meeting schedule to reflect times they can meet with Customer Success

**Comment by AnthonyRollins** [comment]
@o-ram we were hoping you could connect your GCal to Hubspot (here are the [instructions](https://scribehow.com/shared/Connect_personal_calendar_to_Hubspot__57kdzZndRMSGKHTOpAn4mw)) We want to make sure we can add your calendar to the [meeting group](https://app.hubspot.com/meetings/5519226/link/5974854) we have for the conference.

@kathrynmsullivan We need to update all the calendar invites you set to `busy` and change them to `free` so people attending the conference can still choose those times to meet with us.

**Comment by o-ram** [comment]
@AnthonyRollins I think my calendar was already connected, but only for logging, so I just checked the box to allow "Meeting Scheduling Pages Sync" so it should be able to be added to the group. Let me know if I still need to adjust my settings though.

**Comment by o-ram** [comment]
I think I was able to add myself to the group! cc @kathrynmsullivan

**Comment by AnthonyRollins** [comment]
We can close this out as all steps have been completed.
