### ISSUE TITLE
[Data Import] CTA attendee list

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/customer-success#363]
## To-Do
- [x] Add conference data `Caltransit 2023 Fall Expo` 
- [x] Add `vendor type` to all attendees
- [ ] Add meeting details for [Caltransit sessions](https://caltransit.org/Events/Annual-Conferences/Fall-Conference-Expo)
