### ISSUE TITLE
Follow up on CTA

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/customer-success#370]
### To-Dos
- [ ] Follow up on [tasks lists](https://app.hubspot.com/reports-dashboard/5519226/view/11629822).
- [x] #371
- [ ] Add new items to https://github.com/cal-itp/customer-success/issues/358
- [ ] Discuss the conferences we should attend in 2024
