### ISSUE TITLE
Update Customer Success slide in the All hands deck

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/customer-success#386]
[All hands deck draft](https://docs.google.com/presentation/d/17RCNpKx-q36KNlp9Snc2JpLOSdddr3zRikaY03h3D0Q/edit#slide=id.g25546f8b272_0_3)

### To-Dos
- [ ] Update slide 20 with Customer Success accomplishments
- [ ] On slide 20, consider including metrics on "How many transit agencies we spoke to in 2023" and "How much activity for 2023". See about including the number of agencies in each tier.
- [ ] Add a new slide to include 4-5 quotes from past months or conference events (include some photos)

**Comment by AnthonyRollins** [comment]
@o-ram I added some initial thoughts for the all-hands deck slides. There seems to be some interest in adding a slide on quotes from other agencies to include in the all-hand deck slides.

**Comment by o-ram** [comment]
Slides updated and presented during the 12/14 all-hands
