### ISSUE TITLE
Improvements to monthly report

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/customer-success#410]
Goal: To improve the Customer Success monthly reports by adding new metrics and insights more relevant to the Customer Success team.

Related to #407 

## To-Do
- [x] Make sure the CRM, Account Managers metrics and newsletter metrics are accounted for
- [x] Replace CRM metrics with new details on AM outreach
- [x] Enza to schedule time with Kathryn
- [x] Details in #405 could help with coming up with future metrics and insights.
