### ISSUE TITLE
Import DALAC data

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/customer-success#432]
Working [spreadsheet](https://docs.google.com/spreadsheets/d/1GXYrKTTHXq6YDxd_MuAWUnUSiGt02Ld3haKaly2iMs8/edit#gid=0) for import

## To-Dos
- [x] Find emails and domain names for spreadsheet
- [x] import data into Hubspot
- [x] Create a list of the contacts called DALAC contacts

**Comment by AnthonyRollins** [comment]
https://www.chhs.ca.gov/wp-content/uploads/2023/11/DACLAC-Membership-List-2024-2025.pdf
https://www.chhs.ca.gov/wp-content/uploads/2023/11/DACLAC-Member-Bios-2023-2025.pdf
https://www.chhs.ca.gov/home/committees/disability-and-aging-community-living-advisory-committee/

**Comment by adamglinder-la** [comment]
I've started making my way thorugh this list. Google is my friend. LinkedIn is NOT. 

Basically, I've been finding the website of the corresponding organization and deciphering the organization's template for how they list emails. _alinder@ or adam.linder@_ It's time consuming, but Im making my way down. 

Determined to start checking off some of these outstanding issues!

**Comment by adamglinder-la** [comment]
Completed. Double checked addresses. Added into HubSpot. One Contact already existed, all the rest were new. Adjusted Company information. and created a list entitled [DLAC Membership List](https://app.hubspot.com/contacts/5519226/lists/89/filters).

**Comment by AnthonyRollins** [comment]
@adamglinder-la Could you share this DLAC list in Hubspot with Vyki?

**Comment by adamglinder-la** [comment]
@vykster, the import of the DALAC contact list is now complete in HubSpot, live on a list called "[DALAC Membership List](https://app.hubspot.com/contacts/5519226/lists/89/filters)."

Please lmk if there's anything else you need from this!
