### ISSUE TITLE
Create visuals for SOPs

### ISSUE THREAD

**Issue by mariearaneta** [cal-itp/customer-success#481]
### To Do 
@mariearaneta and @ninadinh-la to create visuals for the following SOPs

[G02: Customer Success: Account Manager: Quarterly Check-Ins [SOP]](https://docs.google.com/document/d/156p1a-P7fwU8yY_kWzaR8nyw0LOHXADH6D4g3HCnKxM/edit)
[G09: Account Manager Approach One Pager](https://docs.google.com/document/d/1LBxKkuugRKPFa5e3BoCQM4sIO0miJwLpxSyA8kRd14s/edit#heading=h.31pkpwiacyux)
[CRM 06: Agency Profile Maintenance [SOP]](https://docs.google.com/document/d/1ziQc3UdDUR56N-Yu1iun3iFrCPJhmmMCa7E36yotT2c/edit#heading=h.whbvmp4bdk9g) (this one is pretty messy)
[C01: Connectivity/CS](https://docs.google.com/document/d/1f9z5WM9ZszLiQtlsJxWkgn_FyiFtrIz7MxfgXhDyUkA/edit#heading=h.2xzb0r6ihpk1)

> [Github issue](https://github.com/cal-itp/customer-success/issues/480)

[CRM04: Internal Support Pipeline [SOP]](https://docs.google.com/document/d/1SpxlMizdgIpLHDx9Qi8K4SjQpqOYzcwYmPLTMxBZEmQ/edit)
[CRM03: Support Pipeline [SOP]](https://docs.google.com/document/d/1QudNlgBC1nRdAxQfgrXHr4FcrBKnb7RJ1ZNxUQvAZn4/edit#heading=h.2xzb0r6ihpk1)

**Comment by mariearaneta** [comment]
@ninadinh-la do you have any preference on which you'd like to tackle?

**Comment by mariearaneta** [comment]
@ninadinh-la 

I'm thinking of taking on the following: 

[G02: Customer Success: Account Manager: Quarterly Check-Ins [SOP]](https://docs.google.com/document/d/156p1a-P7fwU8yY_kWzaR8nyw0LOHXADH6D4g3HCnKxM/edit)
[G09: Account Manager Approach One Pager](https://docs.google.com/document/d/1LBxKkuugRKPFa5e3BoCQM4sIO0miJwLpxSyA8kRd14s/edit#heading=h.31pkpwiacyux)
[CRM04: Internal Support Pipeline [SOP]](https://docs.google.com/document/d/1SpxlMizdgIpLHDx9Qi8K4SjQpqOYzcwYmPLTMxBZEmQ/edit)

Let me know what you think. Thanks!

**Comment by ninadinh-la** [comment]
Cool @mariearaneta ! I can take on:
[CRM 06: Agency Profile Maintenance [SOP]](https://docs.google.com/document/d/1ziQc3UdDUR56N-Yu1iun3iFrCPJhmmMCa7E36yotT2c/edit#heading=h.whbvmp4bdk9g) (this one is pretty messy)
[C01: Connectivity/CS](https://docs.google.com/document/d/1f9z5WM9ZszLiQtlsJxWkgn_FyiFtrIz7MxfgXhDyUkA/edit#heading=h.2xzb0r6ihpk1)

https://github.com/cal-itp/customer-success/issues/480
[CRM03: Support Pipeline [SOP]](https://docs.google.com/document/d/1QudNlgBC1nRdAxQfgrXHr4FcrBKnb7RJ1ZNxUQvAZn4/edit#heading=h.2xzb0r6ihpk1)

**Comment by AnthonyRollins** [comment]
@mariearaneta @ninadinh-la Did we make any progress on the list of SOP here? If needed, we update the description to create some to-do lists for each of you. It would look something like this:

### To-Dos for @mariearaneta 
- [ ] [CRM 06: Agency Profile Maintenance [SOP]](https://docs.google.com/document/d/1ziQc3UdDUR56N-Yu1iun3iFrCPJhmmMCa7E36yotT2c/edit#heading=h.whbvmp4bdk9g) (this one is pretty messy)
- [ ] [C01: Connectivity/CS](https://docs.google.com/document/d/1f9z5WM9ZszLiQtlsJxWkgn_FyiFtrIz7MxfgXhDyUkA/edit#heading=h.2xzb0r6ihpk1)
- [ ] https://github.com/cal-itp/customer-success/issues/480
- [ ] [CRM03: Support Pipeline [SOP]](https://docs.google.com/document/d/1QudNlgBC1nRdAxQfgrXHr4FcrBKnb7RJ1ZNxUQvAZn4/edit#heading=h.2xzb0r6ihpk1)

**Comment by mariearaneta** [comment]
@AnthonyRollins I am not sure about Nina, but I haven't put in much work on this yet. I'll add this to-do list to the description. 

Another note - Do you think we should hold off while Caitlin revises some of these SOPs?

**Comment by ninadinh-la** [comment]
@AnthonyRollins @mariearaneta I have not started to revamp these SOPs either. The to-do list would be helpful.

I also wonder about Marie's question^ is Caitlin going to revise these?

**Comment by AnthonyRollins** [comment]
@ninadinh-la @mariearaneta I wouldn't worry about any changes to the SOPs so I would go ahead and make edits and update with visuals.

**Comment by mariearaneta** [comment]
@ninadinh-la FYI I'm moving this to Sprint 16

**Comment by ninadinh-la** [comment]
@laneymangan It has been so long that I can't even recall the purpose of the visuals. I would say lets "not do" and note to revisit the concept in "needs research" if you think that's necessary.

**Comment by laneymangan** [comment]
@ninadinh-la @mariearaneta this came out of our very first in person workshop back when you first started--we thought it might be a helpful way for you to familiarize yourselves with our SOPs by reviewing them and creating charts/tables/visuals that would make SOPs more digestible. At this point, I'm fine with marking it as not doing, unless @o-ram has any objections!

**Comment by o-ram** [comment]
Closing and marking it as "not doing"! We can always reopen it if this becomes something we want to do again, and have the capacity to do so.
