### ISSUE TITLE
Push notes from Hubspot to Slack

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/customer-success#495]
To streamline the CS team's update to Cal-ITP leadership, we need a way to pull out our updates from Hubspot. Typically, the CS team adds updates about vendors and transit agencies via notes in Hubspot. CS would like a way to push notes created by Hubspot users into a new Cal-ITP channel in Slack. Ideally, we should only pull in the notes from the new `vendor object` and companies with `Company Type = Transit Agency.` 

We will need to create a new Slack channel named `cs-updates` for all the Hubspot notes. This would allow the CS team to see all the notes in one place and emoji react to the notes that should be included in a bi-monthly update to Cal-ITP leadership.

## Implementation plan

Using a GitHub Actions workflow that runs on a schedule (e.g. every hour):

### Step 1

- [x] Download the artifact storing `last_note_id`

### Step 2

A `python` script that:

- [x] Parses `last_note_id` from artifact
  - [x] Artifact won't exist initially, `last_note_id` will be empty
- [x] Get all notes since `last_note_id` https://developers.hubspot.com/docs/api/crm/notes
  - [x] Use `after` parameter with value of `last_note_id` in API call
  - [x] Include `associations` for: `companies` and `vendors`
  - [x] May need to page through multiple pages, increase `limit` for page size
    - [x] Configure this with an input and/or GitHub Actions `variables`
  - [x] Re-encode new `last_note_id` using the `paging.next.after` property from the last API response
- [x] For each note in the API response list:
  - [x] If it has no body, skip
  - [x] If it has no author/creator, skip 
  - [x] If it has no associations, skip
  - [x] If it has a `company` association: check if `company_type == Transit Agency`; if not, skip
  - [x] If the note is not being skipped:
    - [x] Get the user's first name associated to `properties.hs_created_by` (the user's ID)
    - [x] Get a company's name from the associated company ID
    - [x] Get a vendor's name from the associated vendor ID
    - [x] Add an item (`dict`) to the output list
- [x] Write the output list to a JSON file

### Step 3

A `python` script that:

- [x] Reads the output list from the file
- [x] For each note in the output list:
  - [x] Process the HTML from the note body into something usable
  - [x] Generate a Slack message using the note attributes https://api.slack.com/reference/surfaces/formatting#rich-layouts
  - [x] Post the message to the channel https://api.slack.com/messaging/sending

### Step 4

- [x] Upload and overwrite the existing artifact with the new `last_note_id`

## Additional resources

- [Engagement API](https://developers.hubspot.com/docs/api/crm/notes)

**Comment by AnthonyRollins** [comment]
@o-ram @laneymangan let me know if there is anything missing from the description above.

**Comment by thekaveman** [comment]
@AnthonyRollins @o-ram @laneymangan 

1. Can you please share an example of what the Slack message should look like? E.g. what details from Hubspot do you want in the message?
2. About how many notes per day are being added in Hubspot?

**Comment by AnthonyRollins** [comment]
@thekaveman For your first question, here are the things I think we need to pull out

1. Author of the Note
2. Date the note was created
3. Note description
4. Association data - what company or contact was this note associated to

Here's a screenshot of a test note in our Hubspot sandbox with the above items highlighted 
![Screenshot 2024-06-17 at 4 41 10 PM](https://github.com/cal-itp/customer-success/assets/25047205/19299feb-ad4c-4eea-969c-6fa2e2dc7f1a)

As for the other question, I will let @laneymangan and @o-ram answer that.

**Comment by thekaveman** [comment]
@AnthonyRollins In the original description, you said:

> Ideally, we should only pull in the notes from the new vendor object and companies with Company Type = Transit Agency.

Then in the reply above, you said:

> Association data - what company or contact was this note associated to

Just to clarify: do we want to pull in notes from _Contacts associated with Transit Agencies and Vendors_ in addition to notes from the Vendor and Transit Agency themselves?

Or do we just want notes attached to Vendors and Transit Agencies?

**Comment by thekaveman** [comment]
@o-ram 

> On the first question, idk if this makes a difference/anything easier, but we do have the option to use snippets in Hubspot

This sounds interesting! But yeah I think for consistency and the sake of the CS team it is probably easier to just pull that data out with the API.

**Comment by AnthonyRollins** [comment]
@thekaveman Response below.

> Or do we just want notes attached to Vendors and Transit Agencies?

Let's go with this option. Most people add notes to the company or vendor record.
