### ISSUE TITLE
External reporting for Vendors brainstorm

### ISSUE THREAD

**Issue by AnthonyRollins** [cal-itp/customer-success#514]
We are drafting the Quarterly report and want to include a section/bullets about vendors' account management. Knowing this, I want to figure out some core milestones or metrics we should be tracking. 

## To-Dos
- [x] Schedule a meeting with Jess, Adam and Scott
- [x] determine metrics and stats to include
- [x] Look for ways to include bar graphs to showcase growth

**Comment by AnthonyRollins** [comment]
@adamglinder-la This isn't an urgent item, but I wanted to put this on your radar and see if we can schedule a meeting between the 4 of us (see To-Dos above).

**Comment by adamglinder-la** [comment]
meeting scheduled for 11:00a on Thursday, August 22nd. 

FYI, I had added a bar graph [within our HubSpot Dashboard](https://app.hubspot.com/reports-dashboard/5519226/view/12960068), but right now it just tracks numbers of our Vendor custom objects in the CRM on a yearly comparison. I'm not quite sure counting Vendors is the best tracking, but it's there for now and we can discuss in the meeting which metrics or stats will be important for the CS team.

**Comment by adamglinder-la** [comment]
Scott and I are meeting this week to put pen to paper and create long term goals. This will be the framework for external reporting as we move into the new year.

**Comment by adamglinder-la** [comment]
Spoke with Vyki this week on this. She expects a concrete plan by end of January. I'm working on it this week and will clue Scott in when he returns. Perhaps we were overthinking this, the example she gave is:

“My goal is to double the numbers of Vendors we are working with.” 
Prioritize NUMBERS. Small report inside much larger quarterly report. 
- Update with Vendor Objects
- Any Outreach Lists
- Any Agency requests, etc.

**Comment by AnthonyRollins** [comment]
@adamglinder-la These are numbers we want to have, but we should talk about what stories we can pull from the vendors that showcase why Cal-ITP is helpful to that group of people.

**Comment by adamglinder-la** [comment]
Per the conversation on Slack with Jess, I believe we have brainstormed this sufficiently. I will draft a first Vendor specific blurb this week to be included in 2-week external report and as news dictates it, we can include big items in the Quarterly Report.
