### ISSUE TITLE
Remix tracking list - launch and initial outreach push

### ISSUE THREAD

**Issue by o-ram** [cal-itp/customer-success#532]
- [x] Update pipeline (as an MVP, pipeline will continue to grow and change as the program evolves)
- [x] Draft pipeline guide 
- [x] Draft SOP
- [x] Fold guide and SOP into the campaign guide doc
- [x] Reach out to Remix priority and 5311 agencies (tracked as tasks in Hubspot)

**Comment by AnthonyRollins** [comment]
Added this as a `low` priority until it is ready.

**Comment by o-ram** [comment]
- The Remix pipeline has been created and is actively being used. 
- The pipeline guide and SOP are roughly drafted and were moved into the campaign guide. Both drafts will continue to be developed as the Remix process is further defined.
- Hubspot tasks are created for all Remix outreach.

Based on the above, this issue has been completed and is being closed.
